name: mycms
description: cms

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  badges: ^3.1.2
  readmore: ^3.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  assets:
    - assets/app_images/
    - .env